kind: Route
apiVersion: route.openshift.io/v1
metadata:
# set your user name
  {{ .Release.Name }}-route:  user8-hello-world
spec:
  to:
    kind: Service
# set your user name
    {{ .Release.Name }}-service:  user8-hello-world
    weight: 100
  port:
    {{ .Values.service.servicePort }}: 8080
  wildcardPolicy: None